--insert into cliente(id cliente, nome, renda)
--values(1, 'Davi Rocha', 300);
--
--insert into cliente(id cliente, nome, renda)
--values(2, 'Danizita', 500);
--
--insert into cliente(id cliente, nome, renda)
--values(3, 'Catapimbas', 1000);